Vagrant.configure("2") do |config|
  config.ssh.insert_key = true
  config.ssh.keep_alive = true


  config.vm.define "master" do |master|
    master.vm.box = "bento/ubuntu-20.04"
    master.vm.hostname = "master"
    master.vm.network "private_network", ip: "192.168.56.4"
    master.vm.network "private_network", ip: "192.168.57.4"
  end
  config.vm.define "worker" do |worker|
    worker.vm.box = "bento/ubuntu-20.04"
    worker.vm.hostname = "worker"
    worker.vm.network "private_network", ip: "192.168.56.5"
    worker.vm.network "private_network", ip: "192.168.57.5"
  end

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "3072"
    vb.cpus = "4"
  end
  config.vm.provision :shell, path: "./bootstrap.sh"
end